name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build jar with Maven in backend
        working-directory: ./backend
        run: mvn -B package -DskipTests

      - name: Build Docker image
        working-directory: ./backend
        run: docker build --build-arg JAR_FILE=target/youlai-boot.jar -t youli-app .

      - name: Save image as tar
        run: docker save youli-app > youli-app.tar

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "youli-app.tar"
          target: "/tmp"
          debug: true
          use_insecure_cipher: true  # 强制使用旧的加密算法以兼容 ssh-rsa 密钥

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          use_insecure_cipher: true  # 强制使用旧的加密算法以兼容 ssh-rsa 密钥
          script: |
            docker load < /tmp/youli-app.tar
            docker stop youli-app || true
            docker rm youli-app || true
            docker run -d --restart=unless-stopped \
              --name youli-app \
              -p 8989:8989 \
              youli-app
